### ISSUE TITLE
Exporting and importing critters

### ISSUE THREAD

**Issue by lynn** [lynn/wordpet#2]
Some way to export/import critters (and the corpuses they’re trained on) would be swell! This would double as a way to share them, and to “save your game and load it” (maybe we could automate the latter a little better (web storage???))

**Comment by noelleleigh** [comment]
Using LocalStorage might be a good idea?

**Comment by lynn** [comment]
You can now export and import your critters to and from JSON files; also, they persist in LocalStorage.
